server: 
  host: "0.0.0.0"
  port: :8080
session_secret: "setOnProducation"
gin_mode: "debug"
log_level: "debug"
mysql_dsn: "root:123456@tcp(127.0.0.1:3306)/gingo?charset=utf8mb4&parseTime=True&loc=Local"
redis:
  addr: "127.0.0.1:6379"
  pass: "123456"
  db: "0"
es:
  url: "http://172.18.0.2:9200"
  user: "elastic"
  pass: "changme"